---
#
# First we prepare the manifest file for the cloud controller
#
- name: Prepare manifest file
  template:
    src: os_cloud_controller.yaml.j2
    dest: "{{state_dir}}/config/os_cloud_controller.yaml"

- name: Apply the newly generated manifest file 
  shell: |
    kubectl --kubeconfig={{state_dir}}/config/admin-kubeconfig apply -f {{state_dir}}/config/os_cloud_controller.yaml
