---
- name: Download base image
  get_url:
    dest: "/home/{{os.install_node.user}}/base.img"
    url: "{{base_image_url}}"
- name: Upload image into Glance 
  os_image:
    auth: "{{os.auth}}"
    auth_type: "password"
    name: "{{base_image_name}}"
    owner: "k8s"
    region_name: "{{os.region_name}}"
    state: present
    filename: "/home/{{os.install_node.user}}/base.img"
- name: Create management network
  os_network:
    auth: "{{os.auth}}"
    auth_type: password
    external: no
    name: "{{k8s_mgmt_network_name}}"
    shared: false
    state: present
- name: Create subnet on management network
  os_subnet:
    auth: "{{os.auth}}"
    auth_type: password
    enable_dhcp: yes
    gateway_ip: "{{k8s_mgmt_network_gateway_ip}}"
    cidr: "{{k8s_mgmt_network_cidr}}"
    network_name: "{{k8s_mgmt_network_name}}"
    name: "{{k8s_mgmt_subnet_name}}"
    state: present
    allocation_pool_start: "{{k8s_mgmt_network_pool_start}}"
    allocation_pool_end:  "{{k8s_mgmt_network_pool_end}}"
- name: Create router 
  os_router:
    auth: "{{os.auth}}"
    auth_type: password
    interfaces:
      "{{k8s_mgmt_subnet_name}}"
    name: "{{k8s_mgmt_network_router_name}}"
    network: "{{os.network.external_network_name}}"
