---
- name: Create manifest file for config map
  template:
    src: webhook_policy_configmap.yaml.j2
    dest: "{{state_dir}}/config/webhook_policy_configmap.yaml"

- name: Apply config map 
  shell: |
    kubectl --kubeconfig {{state_dir}}/config/admin-kubeconfig apply -f {{state_dir}}/config/webhook_policy_configmap.yaml