---
# We use a separate CA for the etcd installation. These variables define the location 
# of key and certificate
etcd_ca_private_key: "{{state_dir}}/ca/etcd_ca.rsa"
etcd_ca_cert: "{{state_dir}}/ca/etcd_ca.crt"
# The API server connects to the etcd using these credentials
# These need to be certificates issued by the CA above
apiserver_etcd_client_key: "{{state_dir}}/k8s_certs/apiserver_etcd_client.rsa"
apiserver_etcd_client_cert: "{{state_dir}}/k8s_certs/apiserver_etcd_client.crt"
# The TLS server key and server certificate, issues by the CA above as well
etcd_server_cert: "{{state_dir}}/k8s_certs/etcd_server.crt"
etcd_server_key: "{{state_dir}}/k8s_certs/etcd_server.rsa"
