#
# Build dynamic inventory from config file
#
- name: Read config.yaml and build inventory
  hosts: localhost 
  become: no
  vars:
    state_dir: "{{playbook_dir}}/../.state"
  pre_tasks:
    - name: Read configuration
      include_vars:
        file: "{{state_dir}}/config/config.yaml"
  roles:
    - parse_config
  
- name: Parse configuration on all hosts
  hosts: all
  gather_facts: no
  tasks:
  - name: Read configuration
    include_vars:
      file: "{{state_dir}}/config/config.yaml"
  - name: Wait for machine to become reachable
    wait_for_connection:
      delay: 3
      sleep: 5

- name: Make sure that public install_node IP in cluster.yaml is up to date
  hosts: localhost
  become: no
  gather_facts: no
  tasks: 
    - name: Update install_node IP address
      lineinfile:
        line:   "            ansible_ssh_host: {{os.install_node.ip}} #__install_node_ip__"
        regexp: ".+#__install_node_ip__"
        state: present
        path: "{{state_dir}}/config/cluster.yaml"