---
#
# Create manifest file
#
- name: Create manifest file for controller
  template:
    src: kuryr_controller.yaml.j2
    dest: "{{state_dir}}/config/kuryr_controller.yaml"

- name: Apply manifest file for controller 
  shell: 
    kubectl apply --kubeconfig {{state_dir}}/config/admin-kubeconfig -f {{state_dir}}/config/kuryr_controller.yaml 

- name: Create manifest file for daemon
  template:
    src: kuryr_daemon.yaml.j2
    dest: "{{state_dir}}/config/kuryr_daemon.yaml"

- name: Apply manifest file for daemon
  shell: 
    kubectl apply --kubeconfig {{state_dir}}/config/admin-kubeconfig -f {{state_dir}}/config/kuryr_daemon.yaml 

