---
- name: Initial node setup
  hosts: worker_nodes, master_nodes
  become: yes 
  roles:
    - k8s_node_setup


#
# There are some additional certificates that we can only create now, once all
# IP addresses are known
#
- name: Create additional certificates 
  hosts: localhost
  become: no
  vars:
    state_dir: "{{playbook_dir}}/../.state"
  roles:
    - late_certs

- name: Install etcd on master node 
  hosts: master
  become: yes
  roles:
    - etcd

    
