---
- name: Initial node setup
  hosts: worker_nodes, master_nodes
  become: yes 
  roles:
    - k8s_node_setup

- name: Read cluster configuration 
  hosts: install_node, localhost
  become: no 
  tasks:
    - name: Read cluster configuration
      include_vars:
        file: "{{state_dir}}/config/config.yaml"


#
# There are some additional certificates that we can only create now, once all
# IP addresses are known
#
- name: Create additional certificates 
  hosts: localhost
  become: no
  vars:
    state_dir: "{{playbook_dir}}/../.state"
  roles:
    - late_certs

- name: Install etcd on master node 
  hosts: master
  become: yes
  roles:
    - etcd

    
- name: Install Kubernetes API server 
  hosts: master
  become: yes
  vars:
    kube_apiserver_binary_url: https://storage.googleapis.com/leftasexercise.com/kube-binaries/kube-apiserver
  roles:
    - kubernetes_apiserver


- name: Configure proxy server on install node if possible to proxy API server 
  hosts: install_node 
  become: yes 
  roles:
    - api_proxy
  
  
- name: Create kubeconfig file for cluster admin
  hosts: localhost 
  become: no
  vars:
    state_dir: "{{playbook_dir}}/../.state"
    client_key_file: "{{state_dir}}/k8s_certs/admin_client.rsa"
    client_cert_file: "{{state_dir}}/k8s_certs/admin_client.crt"
    cluster_ca_file: "{{state_dir}}/ca/k8s_ca.crt"
    kubeconfig_dest: "{{state_dir}}/config/admin-kubeconfig"
    cluster_endpoint: "https://{{os.install_node.ip}}:6443"
    cluster_name: "my-cluster"
    user_name: "admin"
  roles:
    - kubeconfig