---
- name: Copy TLS key pair 
  copy:
    src: "{{controller_manager_key}}"
    dest: "/etc/kubernetes/pki/controller_manager.rsa"
- name: Copy TLS server certificate
  copy:
    src: "{{controller_manager_cert}}"
    dest: "/etc/kubernetes/pki/controller_manager.crt"

  
- name: Copy kubeconfig file
  copy:
    dest: "/etc/kubernetes/pki/kube-controller-manager-config" 
    src: "{{controller_manager_kubeconfig}}"

- name: Install controller-manager binary
  get_url:
    url: "{{kube_controller_manager_binary_url}}"
    owner: root
    group: root
    mode: 0711
    dest: "/usr/local/bin/kube-controller-manager"

- name: Generate systemd unit file for controller manager 
  template: 
    src: kube-controller-manager.service.j2
    dest: /lib/systemd/system/kube-controller-manager.service
    owner: root 
    group: root 
    mode: 0644

- name: Enable and start service 
  service:
    name: kube-controller-manager
    enabled: yes
    state: restarted

