- name: Set static route
  shell: |
    ip route add 10.1.0.0/16 via {{os_router_external_ip}} 
    exit 0
- name: Add security group rule
  os_security_group_rule:
    auth: "{{os.auth}}"      
    auth_type: password
    direction: ingress
    remote_ip_prefix: 172.16.0.1/32
    security_group: "node_security_group"
    state: present
- name: Make sure Docker and python3-pip are installed
  apt:
    force_apt_get: yes 
    update_cache: no
    name: "{{item}}"
    state: present
  loop:
    - docker.io
    - python3-pip
- name: Use custom systemd unit definition for dockerd to disable iptables 
  template:
    dest: /lib/systemd/system/docker.service
    src: docker.service.j2
- name: Restart service 
  service:
    daemon_reload: yes
    state: restarted 
    name: docker
- name: Install docker-py
  shell: |
    pip3 install docker-py
- name: Make sure that we have kubectl on the access node
  get_url:
    url: "{{kubectl_binary_url}}"
    owner: root
    group: root
    mode: 0711
    dest: "/usr/local/bin/kubectl"
- name: Copy kubeconfig file to access node
  copy: 
    src: "{{state_dir}}/config/admin-kubeconfig"
    dest: "/home/{{os.access_node.user}}/admin-kubeconfig"
- name: Create manifest file for NGINX prerequisites
  template:
    src: nginx_prerequisites.yaml.j2
    dest: "/home/{{os.access_node.user}}/nginx_prerequisites.yaml"
- name: Apply manifest file
  shell: |
    kubectl \
      --kubeconfig=/home/{{os.access_node.user}}/admin-kubeconfig \
      apply -f /home/{{os.access_node.user}}/nginx_prerequisites.yaml
- name: Pull image
  docker_image: 
    build:
      pull: yes
    source: pull
    name: "{{nginx_controller_image}}"
    state: present
- name: Start controller 
  docker_container:
    auto_remove: no
    command: 
      - /nginx-ingress-controller
      - --configmap=ingress-nginx/nginx-configuration
      - --configmap=ingress-nginx/nginx-configuration
      - --tcp-services-configmap=ingress-nginx/tcp-services
      - --udp-services-configmap=ingress-nginx/udp-services
      - --annotations-prefix=nginx.ingress.kubernetes.io
      - --kubeconfig=/config/admin-kubeconfig
      - --apiserver-host=https://{{os.access_node.ip}}:6443
      - --http-port=8080
      - --https-port=4433
      - --disable-catch-all
      - --ingress-class=nginx
      - --publish-status-address={{os.access_node.ip}}
      - --update-status=true
    env:
      POD_NAME: nginx-controller-dummy
      POD_NAMESPACE: ingress-nginx
    network_mode: host
    detach: yes
    image: "{{nginx_controller_image}}"
    name: nginx_ingress_controller
    volumes: 
      - /home/{{os.access_node.user}}:/config:ro
    restart_policy: "always"
    state: started


