---
- name: Copy server key pair 
  copy:
    dest: "/etc/kubernetes/pki/keystone_webhook_server.rsa"
    src: "{{keystone_webhook_server_private_key_file}}"

- name: Copy server certificate 
  copy:
    dest: "/etc/kubernetes/pki/keystone_webhook_server.crt"
    src: "{{keystone_webhook_server_cert_file}}"

- name: Copy CA certificate to be able to reach the OpenStack API
  copy:
    dest: "/etc/kubernetes/pki/os_ca.crt"
    src: "{{os_ca_cert_file}}"

- name: Download k8s-keystone-auth binary
  get_url:
    url: "{{keystone_webhook_binary_url}}"
    owner: root
    group: root
    mode: 0711
    dest: "/usr/local/bin/k8s-keystone-auth"

- name: Generate systemd unit file for webhook server 
  template: 
    src: k8s-keystone-auth.service.j2
    dest: /lib/systemd/system/k8s-keystone-auth.service
    owner: root 
    group: root 
    mode: 0644

- name: Enable and start service 
  service:
    name: k8s-keystone-auth
    enabled: yes
    state: restarted

- name: Make sure that /etc/kubernetes/conf exists
  file:
    path: "/etc/kubernetes/conf"
    state: directory

- name: Create webhook configuration file for Kube API server
  template:
    src: webhook.conf.j2
    dest: "/etc/kubernetes/conf/webhook.conf"
    owner: root
    group: root
    mode: 0644

  

