---
# 
# Set up name resolution
#
- name: Ensure entries for all nodes exist in /etc/hosts
  lineinfile:
    line: "{{ item[1].mgmt_ip}} {{ item[0] }}"
    state: present
    path: /etc/hosts
  loop:
    "{{ hostvars.items() | list }}"
  when: 
    item[0] != "install_node"
  loop_control:
    label: "{{ item[0] }}"

#
# Install ifupdown
# 
- name: Install ifupdown
  apt:
    name: ifupdown
    state: present 
    update_cache: yes
    force_apt_get: yes


# 
# Set up underlay network interface
#
- name: Create configuration for ens4
  template:
    src: 90-k8s.j2
    dest: /etc/network/interfaces.d/90-k8s
    mode: 0644
    owner: root
- name: Make sure that file is sourced in /etc/network/interfaces
  lineinfile:
    line: "source /etc/network/interfaces.d/90-k8s"
    state: present
    path: /etc/network/interfaces
- name: Run ifup if needed
  shell: |
    ifup ens4 > /dev/null 2>&1 
    exit 0

#
# Make sure that we have the root CA on every node
#
- name: Make sure that /etc/kubernetes/pki exists 
  file:
    state: "directory"
    dest: "/etc/kubernetes/pki"
- name: Copy root CA certificate
  copy:
    src: "{{k8s_ca_cert}}"
    dest: "/etc/kubernetes/pki/k8s_ca.crt"

#
# Make sure that we have the kubectl binary on every node
#
- name: Install kubectl binary
  get_url:
    url: "{{kubectl_binary_url}}"
    owner: root
    group: root
    mode: 0711
    dest: "/usr/local/bin/kubectl"
