---
- name: Add install host to inventory
  add_host:
    name: access_node
    ansible_ssh_host: "{{os.access_node.ip}}"
    ansible_ssh_user: "{{os.access_node.user}}"
    ansible_ssh_private_key_file: "{{os.access_node.ssh_key}}"
    host_key_checking: false
    ansible_python_interpreter: /usr/bin/python3
