---
- name: Create OVS bridge 
  openvswitch_bridge:
    bridge: "{{bridge_name}}"
    fail_mode: standalone
    state: present
- name: Create patch port
  openvswitch_port:
    bridge: "{{bridge_name}}"
    port: "{{patch_port_local_name}}"
    set: "interface {{patch_port_local_name}} type=patch options:peer={{patch_port_peer_name}}"
- name: Create VXLAN ports pointing to all nodes 
  openvswitch_port:
    bridge: "{{bridge_name}}"
    port: "vxlan-{{item}}"
    set: "interface vxlan-{{item}} type=vxlan options:remote_ip={{item}} options:key={{vxlan_id}}"
  loop:
    "{{vxlan_nodes}}"
- name: Assign IP address to internal interface
  shell: |
    ip addr add {{bridge_ip_address}} dev {{bridge_name}}
    exit 0
- name: Bring up interface
  command: ip link set dev {{bridge_name}} up
- name: Set MTU 
  command: ip link set dev {{bridge_name}} mtu {{bridge_mtu}}
- name: Make this configuration persistent
  template:
    src: 91-openstack.j2
    dest: /etc/network/interfaces.d/91-openstack
    mode: 0644
    owner: root
- name: Source configuration in /etc/network/interfaces
  lineinfile:
    line: "source /etc/network/interfaces.d/91-openstack"
    state: present
    path: /etc/network/interfaces
- name: Change service type of networking.service to simple
  lineinfile:
    line: "Type=simple"
    regexp: "^Type="
    state: present
    path: /lib/systemd/system/networking.service
- name: Restart networking.service on failure
  lineinfile:
    line: "Restart=on-failure"
    insertafter: "^Type="
    firstmatch: yes
    state: present
    path: /lib/systemd/system/neutron-openvswitch-agent.service
- name: Set RestartSec in systemd unit file
  lineinfile:
    path: /lib/systemd/system/networking.service
    line: "RestartSec=5"
    insertafter: "Restart=.*"
    state: present
