#!/bin/bash

#
# SSH into a node (master, workerN)
#

if [ $# -ne 1 ]; then
  echo "Usage: ssh_to_node <node_name>"
  exit 1
fi

ssh \
  -t network \
  "source k8s-openrc ; openstack server ssh --identity=os-default-key --login=ubuntu --public $1"